export default function Home() { return <>
  <section className="home-hero about-hero">
    <div><h1 className="name-title">Yuki Atsusaka</h1>
      <p>I am an Assistant Professor in the <a href="https://uh.edu/hobby/" target="_blank" rel="noreferrer">Hobby School of Public Affairs</a> at the University of Houston. I completed my PhD in Political Science and MA in Statistics at Rice University. I also hold an MA in American Studies, with a focus on African American History and Culture, from Doshisha University. In 2022–2023, I was <a href="https://graduate.dartmouth.edu/admissions-financial-aid/funding/fellowships/provosts-fellowship-program" target="_blank" rel="noreferrer">Guarini Dean’s Fellow in the Politics of Race and Ethnicity</a> at Dartmouth College. In 2026–2027, I serve as the Chair of the <a href="https://district-magnitude.github.io/" target="_blank" rel="noreferrer">Representation and Electoral Systems</a> Organized Section at the American Political Science Association.</p>
      <p>My research focuses on three broad fields of electoral systems, race and representation, and political methodology. I develop general theories of how political institutions shape electoral competition and representation, leveraging the cases of preferential electoral systems and minority representation in American politics. Methodologically, I develop statistical methods for the social sciences, including frameworks for analyzing political ranking data.</p>
      <p>My research has appeared or is forthcoming in the <em>American Political Science Review</em>, <em>Political Analysis</em>, and <em>Nature: Scientific Data</em>. My dissertation, <em>Political Methodologies for Electoral Engineering and Minority Representation</em>, received the John W. Gardner Award for the Best Dissertation in Social Sciences. Part of my research has been supported by the National Science Foundation.</p>
      <p className="contact-line"><a href="mailto:atsusaka@uh.edu">Email</a> · <a href="https://scholar.google.com/citations?user=SeyyV8sAAAAJ&hl=en" target="_blank" rel="noreferrer">Google Scholar</a> · <a href="https://github.com/YukiAtsusaka" target="_blank" rel="noreferrer">GitHub</a> · <a href="https://dataverse.harvard.edu/dataverse/harvard?q=Yuki+Atsusaka&fq1=authorName_ss%3A%22Atsusaka%2C+Yuki%22&fq0=dvObjectType%3A%28dataverses+OR+datasets+OR+files%29&types=dataverses%3Adatasets%3Afiles&sort=score&order=" target="_blank" rel="noreferrer">Harvard Dataverse</a> · <a href="https://x.com/Yuki_Atsusaka" target="_blank" rel="noreferrer">Social Media</a></p>
    </div>
    <img src="https://github.com/YukiAtsusaka.png?size=640" alt="Yuki Atsusaka" />
  </section>
</>; }
