import PageIntro from '../../components/PageIntro';

export default function Research(){return <><PageIntro title="Research"><p>Publications and selected working papers.</p></PageIntro><section className="research-page"><h2>Publications</h2><div className="paper-list">
  <p><span className="paper-number">5. </span>Atsusaka, Yuki, and Jordan Holbrook. 2026. <a href="https://www.nature.com/articles/s41597-026-07623-3" target="_blank" rel="noreferrer">“A Dataset of Tabulated Results from American Ranked-Choice Voting Elections.”</a> <em>Nature: Scientific Data</em>.<br/><a href="https://www.archive-rcv.com/" target="_blank" rel="noreferrer">[Project website]</a> <a href="https://doi.org/10.7910/DVN/RCJA9Z" target="_blank" rel="noreferrer">[Replication files]</a> <a href="https://osf.io/preprints/socarxiv/27hgx_v3" target="_blank" rel="noreferrer">[Preprint]</a></p>
  <p><span className="paper-number">4. </span>Atsusaka, Yuki, and Seo-young Silvia Kim. 2025. <a href="https://doi.org/10.1017/pan.2024.33" target="_blank" rel="noreferrer">“Addressing Measurement Errors in Ranking Questions for the Social Sciences.”</a> <em>Political Analysis</em>.<br/><a href="https://sysilviakim.com/rankingQ/" target="_blank" rel="noreferrer">[R package: rankingQ]</a> <a href="https://doi.org/10.7910/DVN/UCTXEF" target="_blank" rel="noreferrer">[Replication files]</a> <a href="https://osf.io/3ys8x_v1" target="_blank" rel="noreferrer">[Preprint]</a></p>
  <p><span className="paper-number">3. </span>Atsusaka, Yuki. 2025. <a href="https://doi.org/10.1017/pan.2024.9" target="_blank" rel="noreferrer">“Analyzing Ballot Order Effects When Voters Rank Candidates.”</a> <em>Political Analysis</em> 33(1): 64–72.<br/><a href="https://doi.org/10.7910/DVN/AJXRCV" target="_blank" rel="noreferrer">[Replication files]</a> <a href="https://doi.org/10.1017/pan.2024.9" target="_blank" rel="noreferrer">[Article]</a> <a href="https://doi.org/10.48550/arXiv.2207.07005" target="_blank" rel="noreferrer">[Preprint]</a></p>
  <p><span className="paper-number">2. </span>Atsusaka, Yuki, and Randolph T. Stevenson. 2023. <a href="https://doi.org/10.1017/pan.2021.43" target="_blank" rel="noreferrer">“A Bias-Corrected Estimator for the Crosswise Model with Inattentive Respondents.”</a> <em>Political Analysis</em> 31(1): 134–148.<br/><a href="https://github.com/YukiAtsusaka/cWise" target="_blank" rel="noreferrer">[R package: cWise]</a> <a href="https://doi.org/10.7910/DVN/AHWMIL" target="_blank" rel="noreferrer">[Replication files]</a> <a href="https://arxiv.org/abs/2010.16129" target="_blank" rel="noreferrer">[Preprint]</a></p>
  <p><span className="paper-number">1. </span>Atsusaka, Yuki. 2021. <a href="https://doi.org/10.1017/S000305542100054X" target="_blank" rel="noreferrer">“A Logical Model for Predicting Minority Representation: Application to Redistricting and Voting Rights Cases.”</a> <em>American Political Science Review</em> 115(4): 1210–1225.<br/><a href="https://github.com/YukiAtsusaka/logical" target="_blank" rel="noreferrer">[R package: logical]</a> <a href="https://doi.org/10.7910/DVN/F2OX6O" target="_blank" rel="noreferrer">[Replication files]</a></p>
</div><h2>Selected Working Papers</h2><div className="working-papers"><p><a href="https://osf.io/34bjm/" target="_blank" rel="noreferrer">“Ranking Data in Political Science.”</a> With Shubhangi Singh. <strong><em>Under review.</em></strong> <a href="https://political-rankings.github.io/" target="_blank" rel="noreferrer">[Project website]</a></p><p>“Practical Framework for Ranking Data Analysis in Political Science.” With Theodore Landsman. <strong><em>Under editor review.</em></strong></p><p><a href="https://doi.org/10.1017/S0003055424000314" target="_blank" rel="noreferrer">“Who Do People Blame for Affective Polarization?”</a> With Seo-young Silvia Kim. <strong><em>Under review.</em></strong></p></div></section></>}
